from tkinter import *
from tkinter import Tk, Label, font
class Mainpage:
        def __init__(self, master):
                self.master = master
                self.titlefnt = font.Font(family='System', size=25, weight='bold')
                self.labelfnt = font.Font(family='System', size=15, weight='bold')
                self.pad = Frame(master, width=600, height=45, bg = "black")
                self.pad1 = Frame(master, width=600, height=45, bg="black")
                self.pad2 = Frame(master, width=600, height=45, bg="black")
                self.pad3 = Frame(master, width=600, height=45, bg="black")
                self.pad4 = Frame(master, width=600, height=45, bg="black")
                self.label = Label(master, text="Jackalope Search Engine", font = self.titlefnt, pady = 10, padx = 5, bg = "black", fg = "white")
                self.label1 = Label(master, text="Server username:", font = self.labelfnt, pady = 10, padx = 5, bg = "black", fg = "white")
                self.label2 = Label(master, text="Server IP Address:", font = self.labelfnt, pady = 10, padx = 5, bg ="black", fg = "white")
                self.entry = Entry(master)
                self.entry1 = Entry(master)
                self.pad.grid()
                self.label.grid()
                self.pad1.grid()
                self.label1.grid()
                self.entry.grid()
                self.pad2.grid()
                self.label2.grid()
                self.entry1.grid()
                self.pad.grid()
                self.label.grid()
                self.pad1.grid()
                self.label1.grid()
                self.entry.grid()
                self.pad2.grid()
                self.label2.grid()
                self.entry1.grid()
                self.pad3.grid()
root = Tk()
root.configure(bg = "black")
gui = Mainpage(root)
root.mainloop()
